name: test
env:
  TZ: "Asia/Tokyo"
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "!main"

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Update Rust
        run: |
          rustup update
          rustc --version
          cargo --version
      - name: build
        run: cargo build --release
#      - name: run
#        run: ./target/release/github-activity --help
